In [2]:
print("Hellow world")

Hellow world


In [1]:
a:list=[1,2,3,4,5]


In [3]:
print(a)


[1, 2, 3, 4, 5]


In [5]:
b=(1,2,3,4,5)



In [6]:
type(b)


tuple

In [8]:
import numpy as np

In [9]:
np.array(a)

array([1, 2, 3, 4, 5])

In [10]:
c=[1,2,3.0]


In [11]:
np.array(c)

array([1., 2., 3.])

In [12]:
print(np.array(c))

[1. 2. 3.]


In [13]:
type(c)

list

In [14]:
np_c=np.array(c)

In [15]:
type(np_c)

numpy.ndarray

In [17]:
np_a=np.array(a)

In [19]:
type(np_a)

numpy.ndarray

In [20]:
a = np.array([1, 2, 3, 4], dtype = np.int32)