In [2]:
print("Hellow world")

Hellow world


In [ ]:
a:list=[1,2,3,4,5]


In [3]:
print(a)


[1, 2, 3, 4, 5]


In [5]:
b=(1,2,3,4,5)



In [6]:
type(b)


tuple

In [ ]:
import numpy as np

In [ ]:
np.array(a)

array([1, 2, 3, 4, 5])

In [10]:
c=[1,2,3.0]


In [11]:
np.array(c)

array([1., 2., 3.])

In [12]:
print(np.array(c))

[1. 2. 3.]


In [13]:
type(c)

list

In [14]:
np_c=np.array(c)

In [15]:
type(np_c)

numpy.ndarray

In [17]:
np_a=np.array(a)

In [19]:
type(np_a)

numpy.ndarray

In [20]:
a = np.array([1, 2, 3, 4], dtype = np.int32)

In [ ]:
import numpy as np

a = np.arange(10, 18).reshape(2,4)
a       # (2, 4) 형상의 다차원 배열로 10에서 17까지의 원소를 가짐

b = np.arange(12).reshape(3,4)
b  # (3, 4) 형상의 다차원 배열로 0에서 11까지의 원소를 가짐

np.concatenate((a, b))   # a 배열의 마지막 원소 다음에 b 배열을 넣는다