## 리스트와 튜플

In [46]:
print("Hellow world")

Hellow world


In [47]:
a:list=[1,2,3,4,5] #:list 자료형을 명시적으로 보여줌


In [48]:
print(a)


[1, 2, 3, 4, 5]


In [49]:
b=(1,2,3,4,5)



In [50]:
type(b)


tuple

## 파이썬 리스트와 넘파이

 ### 다차원 배열의 속성들

In [51]:
import numpy as np #numpy 로드

In [52]:
a=[1,2,3,4,5]
np.array(a) # 리스트를 넘파이 배열(C배열)로 변환

array([1, 2, 3, 4, 5])

In [53]:
b=[1,2,3.0] #파이썬 리스트, 단일이 아닌 혼합 자료형 리스트 가능
b

[1, 2, 3.0]

In [54]:
np.array(b) #자료형 자동 변환

array([1., 2., 3.])

In [55]:
print(np.array(b))

[1. 2. 3.]


In [56]:
type(b)

list

In [57]:
np_b=np.array(b)

In [58]:
type(np_b) #numpy data array

numpy.ndarray

In [59]:
np_a=np.array(a)

In [60]:
type(np_a)

numpy.ndarray

### 자료형 변환 방법

In [61]:
import numpy as np #numpy 로드

a = np.array([1, 2, 3, 4], dtype = np.int32) #자료형 변환 방법1
b = np.array([1, 2, 3, 4], dtype = 'int32') #자료형 변환 방법1

a, b


(array([1, 2, 3, 4], dtype=int32), array([1, 2, 3, 4], dtype=int32))

In [62]:
c=np.array([1,2,3,4], dtype='uint8') #영상처리용 밝기는 256종류

### 다차원 배열과 브로드캐스팅

In [63]:
import numpy as np #numpy 로드

a=[10,20,30]
b=np.array(a)
b=b*10
b

array([100, 200, 300])

In [64]:
a+10 #Error!

TypeError: can only concatenate list (not "int") to list

In [ ]:
b+10

array([110, 210, 310])

In [ ]:
c = np.array([[10, 20, 30], #2행 3열
              [40, 50, 60]])
d = np.array([2, 3, 4]) #1행 3열 -> 캐스팅. 1행을 복사해서 추가
c + d

array([[12, 23, 34],
       [42, 53, 64]])

In [ ]:
c*d #요소곱이다. 벡터의 내적이 아니다.

array([[ 20,  60, 120],
       [ 80, 150, 240]])

### 값 채우기

#### 2.3.1. 고정값 채우기

In [ ]:
import numpy as np

np.zeros((2, 3)) # 2행 3열의 행렬 생성시 모든 값을 0으로

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((2, 3)) # 2행 3열의 행렬 생성시 모든 값을 1로

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.full((2,3), 100) #np.full(2,3,100) 주의
#1차원 배열은 숫자로 받아도 되지만, 2차원 이상부터는 튜플로 받는다.

array([[100, 100, 100],
       [100, 100, 100]])

In [ ]:
np.eye(3) # 3행3열 단위행렬

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
a=np.array(([1,2,3], [4,5,6])) #2행 3열이 3행 2열로 바뀜
a_t=a.T
a_t

array([[1, 4],
       [2, 5],
       [3, 6]])

#### 2.3.2. 연속값 채우기

In [ ]:
np.arange(0, 10) # 0에서 9까지 연속적인 수열을 생성

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [ ]:
np.arange(0.0, 1, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [ ]:
np.linspace(0.1, 1, 10)

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [ ]:
np.linspace(0, 10, 4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [ ]:
#10^0에서 10^5까지 6개의 수를 로그 스케일에서 균일한 간격으로 생성한다.
#numpy.logspace(start, stop, num=50, endpoint=True, \
# base=10.0, dtype=None)
log_a=np.logspace(0,5,6).round(2) # [1, 10, 100, 1000, 10000, 100000]
log_a

array([1.e+00, 1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05])

In [ ]:
np.log10(log_a) #상용로그. 그냥 log는 자연로그다.

array([0., 1., 2., 3., 4., 5.])

## 다차원 배열의 축과 삽입

### insert() 함수

In [67]:
import numpy as np

a = np.array([1, 3, 4]) 
np.insert(a, 1,2) 
#a.insert(1,2)가 아님. 원본을 수정하지 않는것은 함수로 제공됨
#인덱스 1번에 값 2를 추가하라는 명령어임.

array([1, 2, 3, 4])

In [69]:
b=np.array([[1,1],[2,2],[3,3]])
np.insert(b, 1, 4, axis=1)

array([[1, 4, 1],
       [2, 4, 2],
       [3, 4, 3]])

In [71]:
c=np.array([[1,1], [2,2], [3, 3]]) #내가 원한 답
np.insert(c, 1, 4, axis=0)

array([[1, 1],
       [4, 4],
       [2, 2],
       [3, 3]])

### flip() 함수

In [73]:
d=np.array([[1,2,3],[4,5,6]])
np.flip(d, axis=0)

array([[4, 5, 6],
       [1, 2, 3]])

In [74]:
e=np.array([[1,2,3],[4,5,6]])
np.flip(e, axis=1)

array([[3, 2, 1],
       [6, 5, 4]])

In [79]:
image = np.random.randint(0, 256, size=(768, 1024), dtype='uint8')
flipped_image=np.flip(image, axis=1)
print(image)
flipped_image

[[177  43  87 ...  19  92 109]
 [ 94 156  61 ... 249  79 136]
 [215  10  62 ... 192  70 193]
 ...
 [195  28 232 ... 215 149 254]
 [ 30 100   5 ... 129 244 201]
 [169 194 181 ... 206 220  65]]


array([[109,  92,  19, ...,  87,  43, 177],
       [136,  79, 249, ...,  61, 156,  94],
       [193,  70, 192, ...,  62,  10, 215],
       ...,
       [254, 149, 215, ..., 232,  28, 195],
       [201, 244, 129, ...,   5, 100,  30],
       [ 65, 220, 206, ..., 181, 194, 169]],
      shape=(768, 1024), dtype=uint8)

## 인덱싱과 슬라이싱

In [82]:
import numpy as np

a=np.array([[1,2,3],[4,5,6],\
            [7,8,9], [0,1,2]])
print(a[0][0])
print(a[0])
print(a[3])

1
[1 2 3]
[0 1 2]


In [83]:
a[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [84]:
a[:1][0:1]

array([[1, 2, 3]])

In [85]:
rows, cols = a.shape
for i in range(rows):
    for j in range(cols):
        print(a[i][j], a[i, j]) #a[i,j]형식을 선호

1 1
2 2
3 3
4 4
5 5
6 6
7 7
8 8
9 9
0 0
1 1
2 2


### 논리 인덱싱

In [86]:
a=np.array([[1,2,3],[4,5,6],[7,8,9],[0,1,2]])
a[1:, 0:2]

array([[4, 5],
       [7, 8],
       [0, 1]])

In [90]:
a = [[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]]
b=np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])
b % 2 == 0

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [92]:
b[ b % 2 == 0 ] #불리언 인덱싱. 리스트 컴프리헨션보다 빠름

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [93]:
b #값은 변화없다.

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

## 최댓값, 최솟값, 평균값, 정렬

In [97]:
import numpy as np

a = np.array([10, 20, 30])
a.max(), a.min(), a.mean()           # a 배열원소 중 최대값, 최소값을 출력함

(np.int64(30), np.int64(10), np.float64(20.0))

### 자료형 변환

In [98]:
a.astype(np.float64)

array([10., 20., 30.])

### 평탄화, 전치값

In [99]:
b = np.array([[1, 1], [2, 2], [3, 3]])
b.flatten() # 넘파이 다차원 배열의 평탄화 메소드

array([1, 1, 2, 2, 3, 3])

In [102]:
b=np.array([[1,1],[2,2], [3,3]])
b.T

array([[1, 2, 3],
       [1, 2, 3]])

### Sort


In [106]:
c = np.array([35, 24, 55, 69, 19, 99])
c.sort() # 배열의 정렬(오름차순)
c

array([19, 24, 35, 55, 69, 99])

In [107]:
c[::-1] # 내림차순 정렬, c.sort()를 수행했기에 내림차순 정렬이 된 것임.

array([99, 69, 55, 35, 24, 19])

In [108]:
d = np.array([[35, 24, 55], [69, 19, 9], [4, 1, 11]])
d.sort()         # 배열의 정렬, 디폴트 axis는 1
d

array([[24, 35, 55],
       [ 9, 19, 69],
       [ 1,  4, 11]])

In [109]:
d = np.array([[35, 24, 55], [69, 19, 9], [4, 1, 11]])
d.sort(axis=0)   # axis=0 방향 정렬
d

array([[ 4,  1,  9],
       [35, 19, 11],
       [69, 24, 55]])

## append() 축으로 삽입

In [110]:
a = np.array([1, 2, 3])
b = np.array([[4, 5, 6], [7, 8, 9]])
np.append(a, b) # axis=1이 생략. 1차원으로 더해준다.

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [112]:
a = np.array([1, 2, 3])
b = np.array([[4, 5, 6], [7, 8, 9]])
np.append([a], b, axis=0) # 행으로 삽입해 준다. #디멘젼에 주의 [a]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [113]:
np.append([], b) #요럼 평탄화된다.

array([4., 5., 6., 7., 8., 9.])

## reshape()

In [114]:
a = [1, 2, 3, 4, 5, 6, 7, 8]     # 1차원 리스트 a
b = np.reshape(a,(2,4)) # 2행4열 행렬 b
c = np.reshape(a,(4,2)) # 4행2열 행렬 c
b,c

(array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]))

In [116]:
a=np.arange(1,9) 
b=a.reshape(2,2,2) #3차원. 면행열로 만든다.
b


array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [117]:
b[1]

array([[5, 6],
       [7, 8]])

In [118]:
a=np.arange(10).reshape(-1,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [119]:
a.reshape(-1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 난수

In [ ]:
def pseudo_rand(x):
    a = 1103515245
    b = 12345
    m = 2 ** 31
    new_x = (a * x + b) % m
    return new_x

seed = 100 # 초기값을 임의로 설정하자

x = pseudo_rand(seed) # seed를 입력으로 하여 새로운 x를 만들자
print(x)
x = pseudo_rand(x) # x_n을 입력으로 하여 새로운 x_(n+1)을 만들자
print(x)

In [ ]:
import numpy as np

np.random.rand(5)

### 난수 만들기 함수

In [ ]:
np.random.randint(150, 191, size=10)

In [124]:
rnd=np.random.randn(5)*10 + 165# 평균값이 165,표준편차가 10인 값 생성
rnd
# 표준편차 10 -> 분산 100
# randn() 함수는 평균 0, 표준편차 1인 정규분포확률밀도함수
# 더하면 평균이동
# 표준편차가 10을 곱하면 면적인 베리언스(분산)는 스퀘어로 커진다.

array([161.62227756, 150.3774109 , 165.50655991, 159.44564534,
       161.78677999])

In [125]:
rnd.astype(int) #  정수형으로 변환

array([161, 150, 165, 159, 161])

In [122]:
import numpy as np

a = np.arange(10, 18).reshape(2,4)
a       # (2, 4) 형상의 다차원 배열로 10에서 17까지의 원소를 가짐

b = np.arange(12).reshape(3,4)
b  # (3, 4) 형상의 다차원 배열로 0에서 11까지의 원소를 가짐

np.concatenate((a, b))   # a 배열의 마지막 원소 다음에 b 배열을 넣는다

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [133]:
np.random.seed(42) #시드를 제공
nums=np.random.normal(loc=165, scale=10, size=(3,4)).round(2)
nums

array([[169.97, 163.62, 171.48, 180.23],
       [162.66, 162.66, 180.79, 172.67],
       [160.31, 170.43, 160.37, 160.34]])

In [134]:
a=np.arange(10)
np.random.shuffle(a)
a

array([1, 7, 6, 2, 8, 0, 3, 4, 5, 9])

In [135]:
np.random.permutation([2,4,6,8,10])


array([ 2, 10,  6,  8,  4])

## 평균, 분산, 표준편차

In [136]:
import numpy as np

a = np.array([10, 20, 30, 40, 50])
print('a의 평균값 :', a.mean())

a의 평균값 : 30.0


In [143]:
print(f'a.var(): {a.var()}')

a.var(): 200.0


In [147]:
print(f'평균: {a.mean()}, 분산: {a.var()}, 표준편차: {a.std()}')

평균: 30.0, 분산: 200.0, 표준편차: 14.142135623730951


## 벡터화 연산의 성능 첵크

In [150]:
import numpy as np
import time        # 수행시간 측정을 위하여 time 모듈을 가져온다

arr_a = np.random.rand(100)
arr_b = np.random.rand(100)
result = np.zeros(100)

In [155]:
start=time.time()
for i in range(len(arr_a)):
    result[i]=arr_a[i]*(arr_b[i])
end=time.time()
print(f'소요시간: {1000000*(end-start)}us')

소요시간: 71.76399230957031us


In [163]:
start = time.time()
result = arr_a * arr_b # 벡터화 연산 *
end = time.time()
print('소요시간: ',1000000*(end - start),'us')
print('소요시간: {:12.10f}us'.format(1000000*(end - start)))

소요시간:  78.91654968261719 us
소요시간: 78.9165496826us


In [165]:
n_elem = 100000 # 원소의 개수
arr_a = np.random.rand(n_elem)
arr_b = np.random.rand(n_elem)
result = np.zeros(n_elem)


In [169]:
start = 1000*time.time()
for i in range(n_elem): # 명시적인 작업 지시 : C 스타일
    result[i] = arr_a[i] * arr_b[i]

end = 1000*time.time()
print('원소별 접근 방식 소요시간[ms]: ', end - start)

start = 1000*time.time()
result = arr_a * arr_b
end = 1000*time.time()
print('벡터화 연산 수행 소요시간[ms]: ', end - start)

원소별 접근 방식 소요시간[ms]:  20.953857421875
벡터화 연산 수행 소요시간[ms]:  0.399658203125


## 리덕션: 배열을 더 강력하게 만드는 기능

In [170]:
arr = np.array([[1,2,3,4,5],
                [1,2,3,4,5],
                [1,2,3,4,5],
                [1,2,3,4,5],
                [1,2,3,4,5],
               ])
print(np.sum(arr, axis = 0))
print(np.sum(arr, axis = 1))
np.sum(arr, axis=(0, 1)) # axis = (0, 1)은 생략 가능

[ 5 10 15 20 25]
[15 15 15 15 15]


np.int64(75)

In [172]:
import numpy as np
import time

n = 1000
arr = np.random.rand(n, n)

sum_naive = 0
start = time.time()
for i in range(n):
    for j in range(n):
        sum_naive += arr[i,j]
end = time.time()
print(n, 'x', n, "배열의 원소 합", sum_naive, "\n계산 시간: ", end-start)

1000 x 1000 배열의 원소 합 500022.502455821 
계산 시간:  0.11951255798339844


In [173]:
start = time.time()
sum_reduction = np.sum(arr, axis = (0,1))
end = time.time()
print(n, 'x', n, "배열의 원소 합", sum_reduction,"\n계산 시간: ",end-start)

1000 x 1000 배열의 원소 합 500022.502455817 
계산 시간:  0.0016376972198486328


## 배열의 결합


### concatenate, vstack, hstack

In [174]:
import numpy as np

a = np.arange(10, 18).reshape(2,4)
a       # (2, 4) 형상의 다차원 배열로 10에서 17까지의 원소를 가짐

array([[10, 11, 12, 13],
       [14, 15, 16, 17]])

In [175]:
b = np.arange(12).reshape(3,4)
b  # (3, 4) 형상의 다차원 배열로 0에서 11까지의 원소를 가짐

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [176]:
c = np.arange(8).reshape(2,4)
c   # (2, 4) 형상의 다차원 배열로 0에서 7까지의 원소를 가짐

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [177]:
d = list(range(4))
d   # d는 1차원 리스트로 0에서 3까지의 원소를 가짐

[0, 1, 2, 3]

In [178]:
np.concatenate((a, b))   # a 배열의 마지막 원소 다음에 b 배열을 넣는다

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [179]:
np.vstack((a, b)) # a 배열과 b 배열을 수직 방향으로 결합

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [180]:
np.vstack((a, d)) # a 배열과 d 리스트의 결합

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [ 0,  1,  2,  3]])

In [181]:
np.vstack((a, b, d)) # 다차원 배열 3개를 결합

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3]])

In [182]:
np.hstack((a, c))   # 다차원 배열 a, c를 수평으로 결합

array([[10, 11, 12, 13,  0,  1,  2,  3],
       [14, 15, 16, 17,  4,  5,  6,  7]])

### 배열을 결합하는 r_, c_ 클래스와 column_stack() 함수

In [184]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[10, 20, 30], [40, 50, 60]])

In [186]:
np.r_[a, b]  # 행 방향으로 결합 (세로로 쌓기)

array([ 1,  2,  3, 10, 20, 30])

In [187]:
np.c_[a, b]  # 열 방향으로 결합 (옆으로 붙이기)

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [188]:
np.r_[[a], [b]]

array([[ 1,  2,  3],
       [10, 20, 30]])

In [190]:
np.vstack([a,b])

array([[ 1,  2,  3],
       [10, 20, 30]])

In [191]:
np.r_[a, 4,5,6,b]

array([ 1,  2,  3,  4,  5,  6, 10, 20, 30])

In [194]:
np.r_[[9]*3, 5,6]

array([9, 9, 9, 5, 6])

In [195]:
np.r_[c, d]  # 2차원 배열을 axis=0 방향으로 결합한다

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 20, 30],
       [40, 50, 60]])

In [196]:
# a, b를 2차원 배열로 만들어서 axis=0 방향으로 결합
np.r_[a.reshape(-1,1), b.reshape(-1,1)]

array([[ 1],
       [ 2],
       [ 3],
       [10],
       [20],
       [30]])

In [197]:
np.concatenate((a.reshape(-1, 1), b.reshape(-1, 1)), axis=1)

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [198]:
np.c_[a, b]

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [199]:
np.column_stack([a, b])

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [200]:
# c와 d의 전치행렬을 결합시킨다
np.concatenate((c.T, d.T), axis=1)

array([[ 1,  4, 10, 40],
       [ 2,  5, 20, 50],
       [ 3,  6, 30, 60]])