## 리스트와 튜플

In [46]:
print("Hellow world")

Hellow world


In [47]:
a:list=[1,2,3,4,5] #:list 자료형을 명시적으로 보여줌


In [48]:
print(a)


[1, 2, 3, 4, 5]


In [49]:
b=(1,2,3,4,5)



In [50]:
type(b)


tuple

## 파이썬 리스트와 넘파이

 ### 다차원 배열의 속성들

In [51]:
import numpy as np #numpy 로드

In [52]:
a=[1,2,3,4,5]
np.array(a) # 리스트를 넘파이 배열(C배열)로 변환

array([1, 2, 3, 4, 5])

In [53]:
b=[1,2,3.0] #파이썬 리스트, 단일이 아닌 혼합 자료형 리스트 가능
b

[1, 2, 3.0]

In [54]:
np.array(b) #자료형 자동 변환

array([1., 2., 3.])

In [55]:
print(np.array(b))

[1. 2. 3.]


In [56]:
type(b)

list

In [57]:
np_b=np.array(b)

In [58]:
type(np_b) #numpy data array

numpy.ndarray

In [59]:
np_a=np.array(a)

In [60]:
type(np_a)

numpy.ndarray

### 자료형 변환 방법

In [61]:
import numpy as np #numpy 로드

a = np.array([1, 2, 3, 4], dtype = np.int32) #자료형 변환 방법1
b = np.array([1, 2, 3, 4], dtype = 'int32') #자료형 변환 방법1

a, b


(array([1, 2, 3, 4], dtype=int32), array([1, 2, 3, 4], dtype=int32))

In [62]:
c=np.array([1,2,3,4], dtype='uint8') #영상처리용 밝기는 256종류

### 다차원 배열과 브로드캐스팅

In [63]:
import numpy as np #numpy 로드

a=[10,20,30]
b=np.array(a)
b=b*10
b

array([100, 200, 300])

In [64]:
a+10 #Error!

TypeError: can only concatenate list (not "int") to list

In [ ]:
b+10

array([110, 210, 310])

In [ ]:
c = np.array([[10, 20, 30], #2행 3열
              [40, 50, 60]])
d = np.array([2, 3, 4]) #1행 3열 -> 캐스팅. 1행을 복사해서 추가
c + d

array([[12, 23, 34],
       [42, 53, 64]])

In [ ]:
c*d #요소곱이다. 벡터의 내적이 아니다.

array([[ 20,  60, 120],
       [ 80, 150, 240]])

### 값 채우기

#### 2.3.1. 고정값 채우기

In [ ]:
import numpy as np

np.zeros((2, 3)) # 2행 3열의 행렬 생성시 모든 값을 0으로

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((2, 3)) # 2행 3열의 행렬 생성시 모든 값을 1로

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.full((2,3), 100) #np.full(2,3,100) 주의
#1차원 배열은 숫자로 받아도 되지만, 2차원 이상부터는 튜플로 받는다.

array([[100, 100, 100],
       [100, 100, 100]])

In [ ]:
np.eye(3) # 3행3열 단위행렬

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
a=np.array(([1,2,3], [4,5,6])) #2행 3열이 3행 2열로 바뀜
a_t=a.T
a_t

array([[1, 4],
       [2, 5],
       [3, 6]])

#### 2.3.2. 연속값 채우기

In [ ]:
np.arange(0, 10) # 0에서 9까지 연속적인 수열을 생성

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [ ]:
np.arange(0.0, 1, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [ ]:
np.linspace(0.1, 1, 10)

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [ ]:
np.linspace(0, 10, 4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [ ]:
#10^0에서 10^5까지 6개의 수를 로그 스케일에서 균일한 간격으로 생성한다.
#numpy.logspace(start, stop, num=50, endpoint=True, \
# base=10.0, dtype=None)
log_a=np.logspace(0,5,6).round(2) # [1, 10, 100, 1000, 10000, 100000]
log_a

array([1.e+00, 1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05])

In [ ]:
np.log10(log_a) #상용로그. 그냥 log는 자연로그다.

array([0., 1., 2., 3., 4., 5.])

## 다차원 배열의 축과 삽입

### insert() 함수

In [ ]:
import numpy as np

a = np.array([1, 3, 4]) 
np.insert(a, 1,2) 
#a.insert(1,2)가 아님. 원본을 수정하지 않는것은 함수로 제공됨
#인덱스 1번에 값 2를 추가하라는 명령어임.

array([1, 2, 3, 4])

In [69]:
b=np.array([[1,1],[2,2],[3,3]])
np.insert(b, 1, 4, axis=1)

array([[1, 4, 1],
       [2, 4, 2],
       [3, 4, 3]])

In [ ]:
c=np.array([[1,1], [2,2], [3, 3]]) #내가 원한 답
np.insert(c, 1, 4, axis=0)

array([[1, 1],
       [4, 4],
       [2, 2],
       [3, 3]])

### flip() 함수

In [73]:
d=np.array([[1,2,3],[4,5,6]])
np.flip(d, axis=0)

array([[4, 5, 6],
       [1, 2, 3]])

In [74]:
e=np.array([[1,2,3],[4,5,6]])
np.flip(e, axis=1)

array([[3, 2, 1],
       [6, 5, 4]])

In [79]:
image = np.random.randint(0, 256, size=(768, 1024), dtype='uint8')
flipped_image=np.flip(image, axis=1)
print(image)
flipped_image

[[177  43  87 ...  19  92 109]
 [ 94 156  61 ... 249  79 136]
 [215  10  62 ... 192  70 193]
 ...
 [195  28 232 ... 215 149 254]
 [ 30 100   5 ... 129 244 201]
 [169 194 181 ... 206 220  65]]


array([[109,  92,  19, ...,  87,  43, 177],
       [136,  79, 249, ...,  61, 156,  94],
       [193,  70, 192, ...,  62,  10, 215],
       ...,
       [254, 149, 215, ..., 232,  28, 195],
       [201, 244, 129, ...,   5, 100,  30],
       [ 65, 220, 206, ..., 181, 194, 169]],
      shape=(768, 1024), dtype=uint8)

## 인덱싱과 슬라이싱

In [ ]:
import numpy as np

a=np.array([[1,2,3],[4,5,6],\
            [7,8,9], [0,1,2]])
print(a[0][0])
print(a[0])
print(a[3])

1
[1 2 3]
[0 1 2]


In [83]:
a[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [84]:
a[:1][0:1]

array([[1, 2, 3]])

In [ ]:
rows, cols = a.shape
for i in range(rows):
    for j in range(cols):
        print(a[i][j], a[i, j]) #a[i,j]형식을 선호

1 1
2 2
3 3
4 4
5 5
6 6
7 7
8 8
9 9
0 0
1 1
2 2


### 논리 인덱싱

In [86]:
a=np.array([[1,2,3],[4,5,6],[7,8,9],[0,1,2]])
a[1:, 0:2]

array([[4, 5],
       [7, 8],
       [0, 1]])

In [90]:
a = [[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]]
b=np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])
b % 2 == 0

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [92]:
b[ b % 2 == 0 ] #불리언 인덱싱. 리스트 컴프리헨션보다 빠름

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [ ]:
b #값은 변화없다.

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

## 최댓값, 최솟값, 평균값

In [ ]:
import numpy as np

a = np.arange(10, 18).reshape(2,4)
a       # (2, 4) 형상의 다차원 배열로 10에서 17까지의 원소를 가짐

b = np.arange(12).reshape(3,4)
b  # (3, 4) 형상의 다차원 배열로 0에서 11까지의 원소를 가짐

np.concatenate((a, b))   # a 배열의 마지막 원소 다음에 b 배열을 넣는다