In [1]:
import numpy as np

X = np.array([1, 2])     # 입력 벡터 X
W = np.array([0.5, 0.6]) # 가중치 벡터 W 뉴련이 2개라고도 한다.
X * W                    # 두 벡터의 성분별 곱셈

array([0.5, 1.2])

In [2]:
np.sum( X * W ), np.dot(X, W)  # sum함수, dot함수를 사용하여 가중합 구하기

(np.float64(1.7), np.float64(1.7))

In [3]:
X = np.array([1, 2])    # 넘파이 ndarray 객체 X 생성
W = np.array([[1, 2, 3], [4, 5, 6]]) # 2x3 크기의 ndarray 객체 W 생성
A = np.dot(X, W) # 벡터 X와 행렬 W의 내적 계산
print('A =', A)

A = [ 9 12 15]


### AND와 OR 회로를 퍼셉트론으로 만들자

In [ ]:
import numpy as np

def activation(s):
   if s > 0:
       return 1
   else :
       return -1

def perceptron(W, x, b):
   # W와 x의 내적을 계산하고 편향 b를 더함
   tmp = np.dot(W, x) + b
   return activation(tmp)

In [10]:
print('--- 퍼셉트론으로 구현한 AND 회로 ---')
W = np.array([0.5, 0.5])
b = -0.7
for x1, x2 in [(-1, -1), (-1, 1), (1, -1), (1, 1)]:
    x = np.array([x1, x2])
    y = perceptron(W, x, b)
    print('{:3d} {:3d} : {:3d}'.format(x1, x2, y))

--- 퍼셉트론으로 구현한 AND 회로 ---
 -1  -1 :   1
 -1   1 :   1
  1  -1 :   1
  1   1 :   1


**코드수정**


In [12]:
import numpy as np

def activation(s):
   if s > 0:
       return 1
   else :
       return 0

def perceptron(x1, x2, b=-0.7):
   W = np.array([x1, x2])
   tmp = np.sum( W * x ) + b # np.dot(W,x)+b
   #print(x1,'*',W[0],'+',x2,'*',W[1],'+', b, '=', tmp)
   return activation(tmp)

   print('--- 퍼셉트론으로 구현한 AND 회로 ---')
W = np.array([0.5, 0.5])
b = -0.7
for x1, x2 in [(0, 0), (0, 1), (1, 0), (1, 1)]:
    y = perceptron(x1, x2)
    print('{:3d} {:3d} : {:3d}'.format(x1, x2, y))

  0   0 :   0
  0   1 :   1
  1   0 :   1
  1   1 :   1


In [14]:
from sklearn.neural_network import MLPClassifier

from sklearn.linear_model import Perceptron

X=[[0,0], [0,1], [1,0], [1,1]] #입력 값
Y=[0,0,0,1] #AND 게이트의 출력 값
perception = Perceptron()
perception.fit(X, Y)
print(perception.predict(X))



[0 0 0 1]


In [15]:
print(perception.coef_)
print(perception.intercept_)

perception.predict([[0,0], [0,1], [1,0], [1,1]])

[[2. 2.]]
[-2.]


array([0, 0, 0, 1])

In [ ]:
X1=[[0,0], [0,1], [1,0], [1,1]] #입력 값
Y1=[0,1,1,1] #OR 게이트의 출력 값
perception1 = Perceptron()
perception1.fit(X1, Y1)

print(perception1.coef_)
print(perception1.intercept_)

print(perception1.predict(X1))

[0 1 1 1]
[[2. 2.]]
[-1.]


**XOR을 한 번 해볼까?

In [18]:
X2=[[0,0], [0,1], [1,0], [1,1]] #입력 값
Y2=[0,1,1,0] #OR 게이트의 출력 값
perception2 = Perceptron()
perception2.fit(X2, Y2)

print(perception2.coef_)
print(perception2.intercept_)

print(perception2.predict(X2))

[[0. 0.]]
[0.]
[0 0 0 0]


## 멀티레이어 클래서파이어

In [25]:
mlp=MLPClassifier(hidden_layer_sizes=10, max_iter=10000)
mlp.fit(X2, Y2)
print(mlp.predict(X2))
print(mlp.coefs_)
print(mlp.intercepts_)

[0 1 1 0]
[array([[-1.17061486e+00,  1.83511756e+00,  2.59197802e-23,
        -1.36392853e-10,  1.02849069e+00,  2.08109258e-01,
        -1.15596153e+00,  1.18237919e+00, -1.13650899e-13,
        -9.70990302e-01],
       [-1.17068813e+00, -1.16324799e+00, -1.80111058e-04,
         1.94119186e-31,  1.02858199e+00, -3.82443619e-08,
         1.15584227e+00,  1.24123484e+00, -1.05314045e-33,
         9.70817386e-01]]), array([[-1.71577501e+00],
       [ 1.89736870e+00],
       [ 2.70915724e-03],
       [ 2.15224521e-15],
       [-1.65788928e+00],
       [-9.76230498e-02],
       [ 2.13050883e+00],
       [-1.79175470e+00],
       [ 6.78610161e-16],
       [ 1.27266514e+00]])]
[array([ 1.17067413e+00, -4.16074907e-04, -2.46147847e-01, -4.50621311e-01,
       -1.02843858e+00, -2.28733289e-01, -1.24289756e-04, -1.18233273e+00,
       -3.15883668e-01, -5.54300211e-05]), array([-0.46040099])]
