In [3]:
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt

np.random.seed(85)   # 동일한 결과를 얻기위해 85라는 초기값 사용
x = np.arange(0, 10) # 0, 1, 2, 3, 4, 5, 6, 7, 8, 9를 생성
y1 = x * 2           # 0, 2, 4, 6, 8, 10, 12, 14, 16, 18
np.corrcoef(x, y1)

array([[1., 1.],
       [1., 1.]])

In [5]:
x = np.arange(0, 10) # 0, 1, 2, 3, 4, 5, 6, 7, 8, 9를 생성
y2 = x ** 3          # x의 세제곱 값을 원소로 함
np.corrcoef(x, y2).round(2)

array([[1.  , 0.91],
       [0.91, 1.  ]])

In [6]:
x = np.arange(0, 10)                     # 0에서 9사이의 연속적인 수를 생성
y3 = np.random.randint(0, 100, size=10)  # 0에서 1000사이 10개의 난수 생성
np.corrcoef(x, y3)

array([[1.       , 0.5002124],
       [0.5002124, 1.       ]])